# Generated by Django 5.1.3 on 2024-11-26 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('voice_id', models.CharField(max_length=50, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=100)),
                ('campaign_type', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('cost', models.FloatField()),
                ('outcome', models.CharField(max_length=25)),
                ('call_duration', models.FloatField()),
                ('recording', models.URLField()),
                ('summary', models.TextField()),
                ('transcription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=100)),
                ('campaign_type', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], default='Inbound', max_length=35)),
                ('phone_number', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Paused', 'Paused'), ('Completed', 'Completed')], default='Running', max_length=35)),
                ('agent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.agent')),
            ],
        ),
    ]
